---
title: "Preditcting Likelihood of Women being in Parliament By Year and Percentage"
author: "Fadlan Arif"
date: "21/12/2020"r
bibliography: "references.bib"
abstract: 'In Malaysia, majority of leadership based jobs are held by men. And even the jobs that have women in them, they are a small percentage of the total. With the rise in feminism in the world, paper investigates the real world effects by looking into a workplace with power and ominated by men: the parliament. We use the current information we have to predict the likelihood of a women being in parliament. This information could be vital for looking into the future of Malaysia to see if it needs to assess its current workplace ethics and how they incentivize jobs by gender rather than qualifications.'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
women_in_parliament <- read_excel("data/women in parliament.xlsx")
```



```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

